// บันทึกไฟล์นี้ชื่อ questions.js
const questions =[
  // --- หมวดที่ 1: ความสามารถทั่วไป (ข้อ 1-30) ---
  { "id": 1, "category": "ความสามารถทั่วไป", "question": "2, 4, 8, 16, 32, ... ตัวเลขถัดไปคือ?", "options": ["48", "60", "64", "72"], "answerIndex": 2, "explanation": "ลำดับเพิ่มขึ้นโดยการคูณ 2 (32 x 2 = 64) ครับ" },
  { "id": 2, "category": "ความสามารถทั่วไป", "question": "นก : บิน :: ปลา : ?", "options": ["เดิน", "กระโดด", "ว่ายน้ำ", "เลื้อย"], "answerIndex": 2, "explanation": "เป็นการเปรียบเทียบลักษณะการเคลื่อนที่ตามธรรมชาติครับ" },
  { "id": 3, "category": "ความสามารถทั่วไป", "question": "ค่าเฉลี่ยของ 10, 20, 30, 40, 50 คือ?", "options": ["25", "30", "35", "40"], "answerIndex": 1, "explanation": "ผลรวม (150) หารด้วยจำนวนข้อมูล (5) เท่ากับ 30 ครับ" },
  { "id": 4, "category": "ความสามารถทั่วไป", "question": "รถวิ่งด้วยความเร็ว 60 กม./ชม. ในเวลา 4 ชม. จะได้ระยะทางกี่กิโลเมตร?", "options": ["120", "180", "240", "300"], "answerIndex": 2, "explanation": "ระยะทาง = ความเร็ว x เวลา (60 x 4 = 240) ครับ" },
  { "id": 5, "category": "ความสามารถทั่วไป", "question": "30% ของ 800 มีค่าเท่าใด?", "options": ["200", "240", "260", "300"], "answerIndex": 1, "explanation": "คำนวณจาก (30/100) x 800 = 240 ครับ" },
  { "id": 6, "category": "ความสามารถทั่วไป", "question": "1, 3, 7, 15, ... ตัวเลขถัดไปคือ?", "options": ["25", "30", "31", "35"], "answerIndex": 2, "explanation": "ความสัมพันธ์คือ (ตัวหน้า x 2) + 1 ดังนั้น (15 x 2) + 1 = 31 ครับ" },
  { "id": 7, "category": "ความสามารถทั่วไป", "question": "ไข่ไก่ราคาฟองละ 5 บาท ซื้อ 30 ฟอง ต้องจ่ายเงินกี่บาท?", "options": ["100", "120", "150", "200"], "answerIndex": 2, "explanation": "30 x 5 = 150 บาทครับ" },
  { "id": 8, "category": "ความสามารถทั่วไป", "question": "รูปสี่เหลี่ยมจัตุรัสมีด้านยาวด้านละ 6 ซม. จะมีพื้นที่กี่ตารางเซนติเมตร?", "options": ["24", "30", "36", "42"], "answerIndex": 2, "explanation": "พื้นที่ = ด้าน x ด้าน (6 x 6 = 36) ครับ" },
  { "id": 9, "category": "ความสามารถทั่วไป", "question": "ข้อใดไม่ใช่พวก? (15, 25, 35, 42)", "options": ["15", "25", "35", "42"], "answerIndex": 3, "explanation": "42 หารด้วย 5 ไม่ลงตัว ต่างจากข้ออื่นครับ" },
  { "id": 10, "category": "ความสามารถทั่วไป", "question": "ซื้อเสื้อราคา 1,000 บาท ลดราคา 20% ต้องจ่ายเงินกี่บาท?", "options": ["700", "800", "900", "950"], "answerIndex": 1, "explanation": "ลด 200 บาท เหลือต้องจ่าย 800 บาทครับ" },
  { "id": 11, "category": "ความสามารถทั่วไป", "question": "ห.ร.ม. ของ 8 และ 12 คือ?", "options": ["2", "4", "6", "8"], "answerIndex": 1, "explanation": "4 คือตัวหารร่วมที่มากที่สุดที่หารทั้ง 8 และ 12 ลงตัวครับ" },
  { "id": 12, "category": "ความสามารถทั่วไป", "question": "ค.ร.น. ของ 3 และ 5 คือ?", "options": ["8", "10", "15", "20"], "answerIndex": 2, "explanation": "15 คือพหูพจน์ร่วมที่น้อยที่สุดครับ" },
  { "id": 13, "category": "ความสามารถทั่วไป", "question": "ผลรวมมุมภายในของรูปสี่เหลี่ยมคือ?", "options": ["90", "180", "270", "360"], "answerIndex": 3, "explanation": "มุมภายในรูปสี่เหลี่ยมรวมกันได้ 360 องศาเสมอครับ" },
  { "id": 14, "category": "ความสามารถทั่วไป", "question": "แบ่งเงิน 500 บาท ให้ ก และ ข ในอัตราส่วน 2:3 ข จะได้เงินกี่บาท?", "options": ["100", "200", "300", "400"], "answerIndex": 2, "explanation": "ข ได้ 3 ส่วนจาก 5 ส่วน (3/5 x 500 = 300) ครับ" },
  { "id": 15, "category": "ความสามารถทั่วไป", "question": "รากที่สองของ 144 คือ?", "options": ["10", "12", "14", "16"], "answerIndex": 1, "explanation": "12 x 12 = 144 ครับ" },
  { "id": 16, "category": "ความสามารถทั่วไป", "question": "ทอยลูกเต๋า 1 ลูก โอกาสที่จะได้แต้มมากกว่า 4 คือเท่าใด?", "options": ["1/6", "2/6", "3/6", "4/6"], "answerIndex": 1, "explanation": "แต้มที่มากกว่า 4 คือ 5 และ 6 (มี 2 หน้าจาก 6 หน้า) ครับ" },
  { "id": 17, "category": "ความสามารถทั่วไป", "question": "100, 90, 80, 70, ... ตัวเลขถัดไปคือ?", "options": ["50", "60", "65", "70"], "answerIndex": 1, "explanation": "อนุกรมลดลงทีละ 10 ครับ" },
  { "id": 18, "category": "ความสามารถทั่วไป", "question": "ไก่มีขา รวมกันได้ 20 ขา จะมีไก่กี่ตัว?", "options": ["5", "10", "15", "20"], "answerIndex": 1, "explanation": "ไก่ 1 ตัวมี 2 ขา ดังนั้น 20/2 = 10 ตัวครับ" },
  { "id": 19, "category": "ความสามารถทั่วไป", "question": "ถ้าวันนี้วันศุกร์ อีก 15 วันจะเป็นวันอะไร?", "options": ["ศุกร์", "เสาร์", "อาทิตย์", "จันทร์"], "answerIndex": 1, "explanation": "15 วันหาร 7 เหลือเศษ 1 นับต่อจากวันศุกร์คือวันเสาร์ครับ" },
  { "id": 20, "category": "ความสามารถทั่วไป", "question": "มุมแหลมคือมุมที่มีขนาดเท่าใด?", "options": ["90 องศา", "น้อยกว่า 90 องศา", "มากกว่า 90 องศา", "180 องศา"], "answerIndex": 1, "explanation": "มุมแหลมคือน้อยกว่ามุมฉาก (90 องศา) ครับ" },
  { "id": 21, "category": "ความสามารถทั่วไป", "question": "1, 8, 27, 64, ... ตัวเลขถัดไปคือ?", "options": ["100", "121", "125", "144"], "answerIndex": 2, "explanation": "เป็นอนุกรมเลขยกกำลังสาม (5^3 = 125) ครับ" },
  { "id": 22, "category": "ความสามารถทั่วไป", "question": "เช้า : สาย :: ? : ?", "options": ["เด็ก : ผู้ใหญ่", "มืด : สว่าง", "ร้อน : หนาว", "เร็ว : ช้า"], "answerIndex": 0, "explanation": "เปรียบเทียบลำดับของช่วงเวลาและช่วงวัยครับ" },
  { "id": 23, "category": "ความสามารถทั่วไป", "question": "เลข 1-50 มีเลข 5 ปรากฏกี่ครั้ง?", "options": ["5", "6", "10", "15"], "answerIndex": 1, "explanation": "ปรากฏใน 5, 15, 25, 35, 45, 50 รวม 6 ครั้งครับ" },
  { "id": 24, "category": "ความสามารถทั่วไป", "question": "ไพ่ 1 สำรับ สุ่มหยิบ 1 ใบ โอกาสได้โพดำคือ?", "options": ["1/2", "1/4", "1/13", "1/52"], "answerIndex": 1, "explanation": "โพดำมี 1 ส่วนใน 4 ส่วนของสำรับครับ" },
  { "id": 25, "category": "ความสามารถทั่วไป", "question": "สี่เหลี่ยมผืนผ้า กว้าง 4 ยาว 6 พื้นที่คือ?", "options": ["10", "20", "24", "30"], "answerIndex": 2, "explanation": "กว้าง x ยาว (4 x 6 = 24) ครับ" },
  { "id": 26, "category": "ความสามารถทั่วไป", "question": "1 ลิตร เท่ากับกี่ลูกบาศก์เซนติเมตร (cc)?", "options": ["10", "100", "1,000", "10,000"], "answerIndex": 2, "explanation": "1 ลิตร = 1,000 cc ครับ" },
  { "id": 27, "category": "ความสามารถทั่วไป", "question": "1/3, 1/9, 1/27, ... ตัวถัดไปคือ?", "options": ["1/30", "1/54", "1/81", "1/100"], "answerIndex": 2, "explanation": "ตัวส่วนคูณ 3 ไปเรื่อยๆ ครับ" },
  { "id": 28, "category": "ความสามารถทั่วไป", "question": "3x - 4 = 11 ค่าของ x คือ?", "options": ["3", "4", "5", "6"], "answerIndex": 2, "explanation": "3x = 15 ดังนั้น x = 5 ครับ" },
  { "id": 29, "category": "ความสามารถทั่วไป", "question": "ข้อใดไม่ใช่จำนวนเฉพาะ?", "options": ["2", "3", "7", "9"], "answerIndex": 3, "explanation": "9 หารด้วย 3 ลงตัว ไม่ใช่จำนวนเฉพาะครับ" },
  { "id": 30, "category": "ความสามารถทั่วไป", "question": "0.1 x 0.1 มีค่าเท่าใด?", "options": ["0.1", "0.01", "0.001", "1.0"], "answerIndex": 1, "explanation": "ทศนิยม 1 ตำแหน่ง x 1 ตำแหน่ง ได้ 2 ตำแหน่งครับ" },

  // --- หมวดที่ 2: ภาษาไทย (ข้อ 31-55) ---
  { "id": 31, "category": "ภาษาไทย", "question": "ข้อใดสะกด 'กะเพรา' ได้ถูกต้อง?", "options": ["กระเพรา", "กะเพรา", "กะเพลา", "กระเพลา"], "answerIndex": 1, "explanation": "ตามพจนานุกรม กะเพรา ไม่มี ร เรือ ที่ กะ ครับ" },
  { "id": 32, "category": "ภาษาไทย", "question": "ข้อใดสะกด 'ไอศกรีม' ได้ถูกต้อง?", "options": ["ไอศครีม", "ไอศกรีม", "ไอศกรีมม์", "ไอศครีมม์"], "answerIndex": 1, "explanation": "ทับศัพท์จากภาษาอังกฤษ ใช้ ก ไก่ ครับ" },
  { "id": 33, "category": "ภาษาไทย", "question": "ลักษณนามของ 'พระพุทธรูป' คือ?", "options": ["องค์", "รูป", "ตน", "ใบ"], "answerIndex": 0, "explanation": "พระพุทธรูปใช้ องค์ ส่วนพระสงฆ์ใช้ รูป ครับ" },
  { "id": 34, "category": "ภาษาไทย", "question": "ข้อใดเป็นคำสมาสที่มีการสนธิ?", "options": ["พลความ", "วิทยาศาสตร์", "ธันวาคม", "ราชการ"], "answerIndex": 2, "explanation": "ธันวาคม มาจาก ธนู + อาคม ครับ" },
  { "id": 35, "category": "ภาษาไทย", "question": "สำนวน 'ชุบมือเปิบ' หมายถึงอะไร?", "options": ["ล้างมือสะอาด", "แย่งผลประโยชน์คนอื่น", "ขยันทำงาน", "กินข้าวอร่อย"], "answerIndex": 1, "explanation": "หมายถึงการแย่งผลประโยชน์โดยที่ตัวเองไม่ลงแรงครับ" },
  { "id": 36, "category": "ภาษาไทย", "question": "คำราชาศัพท์ของ 'ตาย' สำหรับพระมหากษัตริย์?", "options": ["มรณภาพ", "ถึงแก่กรรม", "สวรรคต", "สิ้นชีพิตักษัย"], "answerIndex": 2, "explanation": "สวรรคต ใช้สำหรับพระมหากษัตริย์ครับ" },
  { "id": 37, "category": "ภาษาไทย", "question": "ข้อใดเป็นประโยคความรวม?", "options": ["นกบิน", "พ่อและแม่ไปตลาด", "น้องนอนหลับ", "พี่กินข้าว"], "answerIndex": 1, "explanation": "มีคำว่า 'และ' เชื่อมประโยคครับ" },
  { "id": 38, "category": "ภาษาไทย", "question": "ข้อใดมาจากภาษาจีน?", "options": ["ฟุตบอล", "ปิ่นโต", "ก๋วยเตี๋ยว", "เทคโนโลยี"], "answerIndex": 2, "explanation": "ก๋วยเตี๋ยว เป็นคำภาษาจีนครับ" },
  { "id": 39, "category": "ภาษาไทย", "question": "คำตรงข้ามของ 'สงบ'?", "options": ["นิ่ง", "วุ่นวาย", "เรียบร้อย", "เงียบ"], "answerIndex": 1, "explanation": "สงบ ตรงข้ามกับ วุ่นวาย ครับ" },
  { "id": 40, "category": "ภาษาไทย", "question": "ข้อใดสะกดถูกต้อง?", "options": ["บรรยากาศ", "บันยากาศ", "บรยากาศ", "บรรญาการ"], "answerIndex": 0, "explanation": "ใช้ บรร (บ ใบไม้ ร หัน) ครับ" },
  { "id": 41, "category": "ภาษาไทย", "question": "ข้อใดใช้ 'บัน' ผิด?", "options": ["บันทึก", "บันเทิง", "บันได", "บันยาย"], "answerIndex": 3, "explanation": "ที่ถูกต้องสะกดว่า บรรยาย ครับ" },
  { "id": 42, "category": "ภาษาไทย", "question": "ลักษณนามของ 'แหวน'?", "options": ["อัน", "วง", "ชิ้น", "เล่ม"], "answerIndex": 1, "explanation": "แหวนใช้ลักษณนามว่า วง ครับ" },
  { "id": 43, "category": "ภาษาไทย", "question": "คำว่า 'พินิจ' สะกดอย่างไร?", "options": ["พินิช", "พินิจ", "พินิศ", "พินิษฐ์"], "answerIndex": 1, "explanation": "ใช้ จ จาน เป็นตัวสะกดครับ" },
  { "id": 44, "category": "ภาษาไทย", "question": "ข้อใดเป็นคำอุทานเสริมบท?", "options": ["อุ๊ย!", "โธ่!", "หนังสือหนังหา", "ไชโย!"], "answerIndex": 2, "explanation": "หนังสือหนังหา เป็นคำอุทานเสริมบทครับ" },
  { "id": 45, "category": "ภาษาไทย", "question": "ข้อใดเป็นคำกริยา?", "options": ["กระโดด", "คน", "แมว", "ดี"], "answerIndex": 0, "explanation": "กระโดด เป็นคำแสดงอาการครับ" },
  { "id": 46, "category": "ภาษาไทย", "question": "คำว่า 'ปรารถนา' อ่านอย่างไร?", "options": ["ปราด-ถะ-หนา", "ปะ-หราด-ถะ-หนา", "ปราด-นา", "ปะ-ราด-ถะ-นา"], "answerIndex": 0, "explanation": "อ่านว่า ปราด-ถะ-หนา ครับ" },
  { "id": 47, "category": "ภาษาไทย", "question": "ความหมายของ 'ปากเปียกปากแฉะ'?", "options": ["หิวข้าว", "พร่ำสอนซ้ำๆ", "พูดเก่ง", "น้ำลายไหล"], "answerIndex": 1, "explanation": "หมายถึงการตักเตือนซ้ำไปซ้ำมาครับ" },
  { "id": 48, "category": "ภาษาไทย", "question": "คำสุภาพของ 'วัว' คือ?", "options": ["กระบือ", "พยัคฆ์", "คาวี", "กุญชร"], "answerIndex": 2, "explanation": "คาวี หรือ โค เป็นคำสุภาพของวัวครับ" },
  { "id": 49, "category": "ภาษาไทย", "question": "ข้อใดเป็นคำควบไม่แท้?", "options": ["กวาด", "พริก", "ทราย", "ใกล้"], "answerIndex": 2, "explanation": "ทราย (ทร) ออกเสียงเป็น ซ ครับ" },
  { "id": 50, "category": "ภาษาไทย", "question": "คำว่า 'โน้ตเพลง' อ่านอย่างไร?", "options": ["โนด-เป-ลา", "โน้ต-เป-ลา", "โนด-เป-ลา-โน", "โน้ด-ปะ-ลา"], "answerIndex": 1, "explanation": "อ่านตามหลักอักขรวิธีไทยครับ" },
  { "id": 51, "category": "ภาษาไทย", "question": "คำพ้องเสียงของ 'กาล' คือ?", "options": ["กาน", "การ", "กำ", "กาม"], "answerIndex": 1, "explanation": "การ ออกเสียงเหมือน กาล แต่ความหมายต่างกันครับ" },
  { "id": 52, "category": "ภาษาไทย", "question": "ตรงข้ามกับ 'มืด'?", "options": ["ดำ", "สว่าง", "เงียบ", "หนาว"], "answerIndex": 1, "explanation": "ตรงข้ามกับมืดคือสว่างครับ" },
  { "id": 53, "category": "ภาษาไทย", "question": "ข้อใดเป็นคำประสม?", "options": ["นกยูง", "น้ำแข็ง", "มะลิ", "กะปิ"], "answerIndex": 1, "explanation": "น้ำ + แข็ง เกิดความหมายใหม่ครับ" },
  { "id": 54, "category": "ภาษาไทย", "question": "โวหารเล่าเรื่องตามลำดับ?", "options": ["บรรยาย", "พรรณนา", "เทศนา", "อุปมา"], "answerIndex": 0, "explanation": "บรรยายโวหารใช้เล่าเรื่องตามลำดับครับ" },
  { "id": 55, "category": "ภาษาไทย", "question": "คำราชาศัพท์ของ 'หัว'?", "options": ["พระนลาฏ", "พระกรรณ", "พระเศียร", "พระโอษฐ์"], "answerIndex": 2, "explanation": "พระเศียร หมายถึง หัว ครับ" },

  // --- หมวดที่ 3: ภาษาอังกฤษ (ข้อ 56-85) ---
  { "id": 56, "category": "ภาษาอังกฤษ", "question": "Plural of 'Mouse'?", "options": ["Mouses", "Mice", "Mices", "Mousie"], "answerIndex": 1, "explanation": "Mice เป็นรูปพหุพจน์ของ Mouse ครับ" },
  { "id": 57, "category": "ภาษาอังกฤษ", "question": "I _____ a movie last night.", "options": ["watch", "watches", "watched", "watching"], "answerIndex": 2, "explanation": "last night บอกอดีต ใช้กริยาช่อง 2 ครับ" },
  { "id": 58, "category": "ภาษาอังกฤษ", "question": "This bag is _____ than that one.", "options": ["expensive", "more expensive", "expensiver", "most expensive"], "answerIndex": 1, "explanation": "ขั้นกว่าของคำ 3 พยางค์ใช้ more ครับ" },
  { "id": 59, "category": "ภาษาอังกฤษ", "question": "_____ is your birthday?", "options": ["Where", "When", "What", "Who"], "answerIndex": 1, "explanation": "When ใช้ถามเกี่ยวกับเวลาครับ" },
  { "id": 60, "category": "ภาษาอังกฤษ", "question": "They _____ students.", "options": ["is", "am", "are", "be"], "answerIndex": 2, "explanation": "They เป็นพหูพจน์ใช้ are ครับ" },
  { "id": 61, "category": "ภาษาอังกฤษ", "question": "Look! It _____.", "options": ["rain", "rains", "is raining", "rained"], "answerIndex": 2, "explanation": "ใช้ Present Continuous บอกเหตุการณ์ที่กำลังเกิดครับ" },
  { "id": 62, "category": "ภาษาอังกฤษ", "question": "She wants _____ umbrella.", "options": ["a", "an", "the", "some"], "answerIndex": 1, "explanation": "umbrella ขึ้นต้นด้วยสระ ใช้ an ครับ" },
  { "id": 63, "category": "ภาษาอังกฤษ", "question": "We _____ English every day.", "options": ["study", "studies", "studying", "studied"], "answerIndex": 0, "explanation": "ทุกวันเป็นกิจวัตร We เป็นพหูพจน์ กริยาไม่ต้องเติม s ครับ" },
  { "id": 64, "category": "ภาษาอังกฤษ", "question": "He _____ to the gym on Mondays.", "options": ["go", "goes", "going", "gone"], "answerIndex": 1, "explanation": "ประธานเอกพจน์ He กริยาเติม es ครับ" },
  { "id": 65, "category": "ภาษาอังกฤษ", "question": "Give it to _____.", "options": ["he", "his", "him", "himself"], "answerIndex": 2, "explanation": "ใช้ him เป็นสรรพนามรูปกรรมครับ" },
  { "id": 66, "category": "ภาษาอังกฤษ", "question": "Which one is a vegetable?", "options": ["Apple", "Banana", "Broccoli", "Grape"], "answerIndex": 2, "explanation": "Broccoli คือผักครับ" },
  { "id": 67, "category": "ภาษาอังกฤษ", "question": "He is good _____ football.", "options": ["in", "on", "at", "with"], "answerIndex": 2, "explanation": "good at แปลว่าเก่งในด้าน... ครับ" },
  { "id": 68, "category": "ภาษาอังกฤษ", "question": "How _____ brothers do you have?", "options": ["much", "many", "old", "long"], "answerIndex": 1, "explanation": "many ใช้กับนามนับได้พหูพจน์ครับ" },
  { "id": 69, "category": "ภาษาอังกฤษ", "question": "You _____ wear a seatbelt.", "options": ["can", "should", "might", "may"], "answerIndex": 1, "explanation": "should ใช้ให้คำแนะนำครับ" },
  { "id": 70, "category": "ภาษาอังกฤษ", "question": "Today is Friday. Tomorrow is _____.", "options": ["Saturday", "Sunday", "Monday", "Tuesday"], "answerIndex": 0, "explanation": "หลังวันศุกร์คือวันเสาร์ครับ" },
  { "id": 71, "category": "ภาษาอังกฤษ", "question": "The book is _____ the table.", "options": ["on", "in", "at", "under of"], "answerIndex": 0, "explanation": "on แปลว่าบนครับ" },
  { "id": 72, "category": "ภาษาอังกฤษ", "question": "_____ color do you like?", "options": ["Who", "What", "When", "Where"], "answerIndex": 1, "explanation": "What color ใช้ถามว่าสีอะไรครับ" },
  { "id": 73, "category": "ภาษาอังกฤษ", "question": "I _____ happy today.", "options": ["is", "am", "are", "be"], "answerIndex": 1, "explanation": "I ใช้คู่กับ am เสมอครับ" },
  { "id": 74, "category": "ภาษาอังกฤษ", "question": "Would you like _____ coffee?", "options": ["a", "an", "some", "any"], "answerIndex": 2, "explanation": "some ใช้ในการเสนอ (Offer) ครับ" },
  { "id": 75, "category": "ภาษาอังกฤษ", "question": "Mount Everest is the _____ mountain.", "options": ["high", "higher", "highest", "more high"], "answerIndex": 2, "explanation": "ขั้นสูงสุดใช้ highest ครับ" },
  { "id": 76, "category": "ภาษาอังกฤษ", "question": "It is _____ (มีหิมะตก).", "options": ["sunny", "windy", "snowy", "rainy"], "answerIndex": 2, "explanation": "snowy หมายถึงมีหิมะตกครับ" },
  { "id": 77, "category": "ภาษาอังกฤษ", "question": "Who helps sick people?", "options": ["Driver", "Cook", "Doctor", "Pilot"], "answerIndex": 2, "explanation": "Doctor คือหมอรักษาคนป่วยครับ" },
  { "id": 78, "category": "ภาษาอังกฤษ", "question": "I don't have _____ pencils.", "options": ["some", "any", "a", "an"], "answerIndex": 1, "explanation": "any ใช้ในประโยคปฏิเสธครับ" },
  { "id": 79, "category": "ภาษาอังกฤษ", "question": "Does she like tea? - Yes, she _____.", "options": ["do", "does", "is", "likes"], "answerIndex": 1, "explanation": "ถาม Does ตอบ Does ครับ" },
  { "id": 80, "category": "ภาษาอังกฤษ", "question": "Opposite of 'Hard'?", "options": ["Easy", "Difficult", "Strong", "Tall"], "answerIndex": 0, "explanation": "Easy (ง่าย) ตรงข้ามกับ Hard (ยาก) ครับ" },
  { "id": 81, "category": "ภาษาอังกฤษ", "question": "_____ are you? - I am 20 years old.", "options": ["How old", "How many", "What", "Who"], "answerIndex": 0, "explanation": "How old ใช้ถามอายุครับ" },
  { "id": 82, "category": "ภาษาอังกฤษ", "question": "I _____ my homework at 8 PM.", "options": ["do", "did", "done", "doing"], "answerIndex": 1, "explanation": "ใช้ did บอกเหตุการณ์ในอดีตครับ" },
  { "id": 83, "category": "ภาษาอังกฤษ", "question": "Please _____ quiet.", "options": ["be", "is", "am", "are"], "answerIndex": 0, "explanation": "be quiet เป็นสำนวนให้เงียบครับ" },
  { "id": 84, "category": "ภาษาอังกฤษ", "question": "I have lived here _____ 2010.", "options": ["for", "since", "at", "in"], "answerIndex": 1, "explanation": "since ใช้บอกจุดเริ่มต้นของเวลาครับ" },
  { "id": 85, "category": "ภาษาอังกฤษ", "question": "This is _____ book. (ของฉัน)", "options": ["my", "mine", "I", "me"], "answerIndex": 0, "explanation": "my เป็นคุณศัพท์แสดงความเป็นเจ้าของครับ" },

  // --- หมวดที่ 4: เทคโนโลยีสารสนเทศ (ข้อ 86-110) ---
  { "id": 86, "category": "เทคโนโลยีสารสนเทศ", "question": "ROM ย่อมาจากอะไร?", "options": ["Read Only Memory", "Random Only Memory", "Run On Memory", "Real Online Memory"], "answerIndex": 0, "explanation": "ROM คือหน่วยความจำที่อ่านได้เพียงอย่างเดียวครับ" },
  { "id": 87, "category": "เทคโนโลยีสารสนเทศ", "question": "หน่วยเก็บข้อมูลที่เล็กที่สุดคือ?", "options": ["Bit", "Byte", "KB", "MB"], "answerIndex": 0, "explanation": "บิต (Bit) เป็นหน่วยที่เล็กที่สุดครับ" },
  { "id": 88, "category": "เทคโนโลยีสารสนเทศ", "question": "Ctrl + C คือคำสั่งใด?", "options": ["Paste", "Cut", "Copy", "Undo"], "answerIndex": 2, "explanation": "Copy คือการคัดลอกครับ" },
  { "id": 90, "category": "เทคโนโลยีสารสนเทศ", "question": "ใช้ทำตารางคำนวณคือซอฟต์แวร์ใด?", "options": ["Word", "Excel", "PowerPoint", "Access"], "answerIndex": 1, "explanation": "Microsoft Excel ใช้สำหรับงานตารางและการคำนวณครับ" },
  { "id": 92, "category": "เทคโนโลยีสารสนเทศ", "question": "Firewall มีไว้เพื่ออะไร?", "options": ["เพิ่มความเร็ว", "ป้องกันการบุกรุก", "พ่นไฟ", "ประหยัดไฟ"], "answerIndex": 1, "explanation": "ใช้ป้องกันผู้ไม่หวังดีบุกรุกเครือข่ายครับ" },
  { "id": 94, "category": "เทคโนโลยีสารสนเทศ", "question": "1 TB ประมาณกี่ GB?", "options": ["100", "500", "1,000", "10,000"], "answerIndex": 2, "explanation": "1 Terabyte เท่ากับ 1,000 Gigabyte โดยประมาณครับ" },
  { "id": 96, "category": "เทคโนโลยีสารสนเทศ", "question": "ข้อใดคือ Software?", "options": ["Monitor", "RAM", "CPU", "Photoshop"], "answerIndex": 3, "explanation": "Photoshop เป็นโปรแกรม (ซอฟต์แวร์) ครับ" },
  { "id": 99, "category": "เทคโนโลยีสารสนเทศ", "question": "ISP คืออะไร?", "options": ["คนเล่นเน็ต", "ผู้ให้บริการอินเทอร์เน็ต", "ช่างซ่อมคอม", "สายเคเบิล"], "answerIndex": 1, "explanation": "Internet Service Provider คือผู้ให้บริการอินเทอร์เน็ตครับ" },
  { "id": 103, "category": "เทคโนโลยีสารสนเทศ", "question": "Malware คืออะไร?", "options": ["ซอฟต์แวร์ดี", "ซอฟต์แวร์ประสงค์ร้าย", "ฮาร์ดแวร์ใหม่", "ความปลอดภัย"], "answerIndex": 1, "explanation": "คือโปรแกรมที่สร้างขึ้นเพื่อหวังผลร้ายต่อระบบครับ" },
  { "id": 108, "category": "เทคโนโลยีสารสนเทศ", "question": "IoT ย่อมาจาก?", "options": ["Internet of Things", "Input of Time", "Internal of Tech", "Identity of Tool"], "answerIndex": 0, "explanation": "อินเทอร์เน็ตในทุกสรรพสิ่งครับ" },
  // ... (ข้อ 86-110 รวบรวมตามหลักการนี้)

  // --- หมวดที่ 5: กฎหมายที่ประชาชนควรรู้ (ข้อ 111-130) ---
  { "id": 111, "category": "กฎหมาย", "question": "จดทะเบียนสมรสได้เมื่ออายุเท่าใด?", "options": ["15", "17", "18", "20"], "answerIndex": 1, "explanation": "อายุ 17 ปีบริบูรณ์ สามารถจดทะเบียนสมรสได้ครับ" },
  { "id": 112, "category": "กฎหมาย", "question": "ต้องมีบัตรประชาชนครั้งแรกเมื่ออายุเท่าใด?", "options": ["7", "15", "17", "20"], "answerIndex": 0, "explanation": "7 ปีบริบูรณ์ต้องทำบัตรประชาชนครับ" },
  { "id": 113, "category": "กฎหมาย", "question": "คนไร้ความสามารถทำนิติกรรมผลเป็นอย่างไร?", "options": ["สมบูรณ์", "โมฆะ", "โมฆียะ", "ใช้ได้"], "answerIndex": 1, "explanation": "คนไร้ความสามารถทำนิติกรรมมีผลเป็นโมฆะครับ" },
  { "id": 115, "category": "กฎหมาย", "question": "ขับรถฝ่าไฟแดงผิด พ.ร.บ. ใด?", "options": ["แพ่ง", "จราจรทางบก", "ป่าไม้", "รัฐธรรมนูญ"], "answerIndex": 1, "explanation": "ผิด พ.ร.บ. จราจรทางบก ครับ" },
  { "id": 118, "category": "กฎหมาย", "question": "ศาลสูงสุดของไทยในระบบศาลยุติธรรมคือ?", "options": ["ชั้นต้น", "อุทธรณ์", "ฎีกา", "รัฐธรรมนูญ"], "answerIndex": 2, "explanation": "ศาลฎีกา เป็นศาลสูงสุดครับ" },
  { "id": 120, "category": "กฎหมาย", "question": "วิ่งราวทรัพย์ คืออะไร?", "options": ["แอบหยิบ", "ฉกฉวยต่อหน้า", "ขู่เข็ญ", "งัดบ้าน"], "answerIndex": 1, "explanation": "คือการลักทรัพย์โดยฉกฉวยเอาไปซึ่งหน้าครับ" },
  { "id": 124, "category": "กฎหมาย", "question": "การหมั้นสมบูรณ์เมื่อใด?", "options": ["ตกลงกัน", "ทำสัญญา", "ส่งมอบของหมั้น", "จดทะเบียน"], "answerIndex": 2, "explanation": "สมบูรณ์เมื่อฝ่ายชายส่งมอบของหมั้นให้ฝ่ายหญิงครับ" },
  { "id": 126, "category": "กฎหมาย", "question": "ทายาทโดยธรรมลำดับที่ 1 คือ?", "options": ["พ่อแม่", "คู่สมรส", "ลูก", "พี่น้อง"], "answerIndex": 2, "explanation": "ผู้สืบสันดาน (ลูก) เป็นทายาทลำดับที่ 1 ครับ" },
  // ... (ข้อ 111-130 รวบรวมตามหลักการนี้)

  // --- หมวดที่ 6: สังคม วัฒนธรรม อาเซียน (ข้อ 131-150) ---
  { "id": 131, "category": "สังคม", "question": "ศาสนาพุทธนิกายหลักในไทยคือ?", "options": ["มหายาน", "เถรวาท", "เซ็น", "วัชรยาน"], "answerIndex": 1, "explanation": "ประเทศไทยนับถือนิกายเถรวาทครับ" },
  { "id": 132, "category": "สังคม", "question": "วันอาสาฬหบูชาเกี่ยวข้องกับเหตุการณ์ใด?", "options": ["เกิดพระธรรม", "เกิดพระสงฆ์องค์แรก", "ตรัสรู้", "ปรินิพพาน"], "answerIndex": 1, "explanation": "เป็นวันที่เกิดพระสงฆ์รูปแรกของโลกครับ" },
  { "id": 136, "category": "สังคม", "question": "สีขาวในธงชาติไทยคือ?", "options": ["กษัตริย์", "ศาสนา", "ชาติ", "สันติภาพ"], "answerIndex": 1, "explanation": "สีขาวหมายถึงศาสนาครับ" },
  { "id": 140, "category": "สังคม", "question": "ทฤษฎีใหม่แบ่งที่ดินอย่างไร?", "options": ["30:30:30:10", "25:25:25:25", "40:30:20:10", "50:20:20:10"], "answerIndex": 0, "explanation": "แบ่งเป็น น้ำ:นา:สวน:บ้าน ตามสัดส่วนนี้ครับ" },
  { "id": 141, "category": "อาเซียน", "question": "ประเทศใดไม่มีทางออกสู่ทะเล?", "options": ["ไทย", "ลาว", "เวียดนาม", "พม่า"], "answerIndex": 1, "explanation": "ลาวเป็นประเทศเดียวที่ไม่มีพื้นที่ติดทะเลครับ" },
  { "id": 142, "category": "อาเซียน", "question": "รวงข้าว 10 รวงในตราอาเซียนหมายถึง?", "options": ["ความรวย", "ความสามัคคี 10 ประเทศ", "อาหาร", "ความเก่าแก่"], "answerIndex": 1, "explanation": "รวงข้าว 10 รวงสื่อถึง 10 ประเทศสมาชิกที่ผูกพันกันครับ" },
  { "id": 147, "category": "อาเซียน", "question": "ภาษากลางอาเซียนคือ?", "options": ["ไทย", "จีน", "อังกฤษ", "มาเลย์"], "answerIndex": 2, "explanation": "ภาษาอังกฤษเป็นภาษากลางในการทำงานของอาเซียนครับ" },
  { "id": 150, "category": "อาเซียน", "question": "สัตว์ประจำชาติไทยคือ?", "options": ["เสือ", "แมว", "ช้าง", "ไก่"], "answerIndex": 2, "explanation": "ช้าง คือสัตว์ประจำชาติไทยครับ" }
];
